name: 'Update maven ~/.m2/settings.xml'
description: 'Greet someone and record the time'
branding: 
  icon: feather
  color: orange
inputs:
  servers:
    description: 'json array of servers to add to settings.xml'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
