name: 'maven-settings-xml-action'
description: 'Update maven ~/.m2/settings.xml'
branding: 
  icon: feather
  color: orange
inputs:
  servers:
    description: 'json array of servers to add to settings.xml'
    required: false
  repositories:
    description: 'json array of repositories to add to settings.xml'
    required: false
runs:
  using: 'node12'
  main: 'src/index.js'
