name: 'Update maven ~/.m2/settings.xml'
description: 'Greet someone and record the time'
branding: 
  icon: feather
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
