on:
  push:
    branches: develop

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:

    - name: Create maven settings.xml
      uses: whelk-io/maven-settings-xml-action@v1
      with:
        servers: '[{"id": "foo", "username": "fu", "password": "bar" }]'
        mirrors: '[{ "id": "nexus", "mirrorOf": "!my-org-snapshots,*", "url": "http://redacted/nexus/content/groups/public" }]'
        repositories: '[{"id": "foo", "url": "https://fu.bar"}]'
        plugin_repositories: '[{"id": "foo-plugin", "url": "https://fu.bar.plugin"}]'

    - run: |
        cat ~/.m2/settings.xml

